apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: registry-creds-controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-creds-controller
  namespace: system
  labels:
    control-plane: registry-creds-controller
spec:
  selector:
    matchLabels:
      control-plane: registry-creds-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: registry-creds-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: alexellis2/registry-creds-controller:0.1.1
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
