name: ci-only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     registry: ghcr.io
      - name: Local build
        id: local_build
        uses: docker/build-push-action@v2
        with:
          outputs: "type=docker,push=false"
          platforms: linux/amd64
          tags: ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Image digest
        run: echo ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Image digest 2
        run: echo ${{ steps.local_build.outputs.digest }}
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: "v0.9.0"
          image: kindest/node:v1.18.8
      - name: Show images
        run: docker images
      - name: Load test image
        run: kind load --loglevel trace docker-image ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Apply CRD
        run: |
          export TAG=${{ github.sha }}
          sed -ie "s/0.2.1/$TAG/g" ./manifest.yaml
          kubectl apply -f ./manifest.yaml
      - name: Check deployment
        run: 
          kubectl rollout status -n registry-creds-system deploy/registry-creds-registry-creds-controller --timeout=2m || kubectl describe -n registry-creds-system deploy deploy/registry-creds-registry-creds-controller
