name: ci-only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Local build
        id: local_build
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64
          load: true # Keep in local image library
          tags: ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Image digest
        run: echo ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Load test image
        run: kind load docker-image ghcr.io/alexellis/registry-creds:${{ github.sha }}
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.4.0
      - name: Apply CRD
        run: |
          export TAG=${{ github.sha }}
          sed -ie "s/0.2.1/$TAG/g" ./manifest.yaml
          kubectl apply -f ./manifest.yaml
      - name: Get deployment
        run: 
          kubectl rollout status -n registry-creds-system deploy/registry-creds-registry-creds-controller

